### ISSUE TITLE
Rover does not work with Terraform 1.0.4

### ISSUE THREAD

**Issue by dmomcilo** [im2nguyen/rover#23]
`docker run --rm -it -p 9000:9000 -v $(pwd):/src --env-file ./.env im2nguyen/rover`
`2021/09/24 10:42:45 Starting Rover...`
`2021/09/24 10:42:45 Initializing Terraform...`
`2021/09/24 10:42:46 Unable to parse Plan: terraform core version not supported by configuration`

`tfenv list`
          `  * 1.0.4 (set by /usr/local/Cellar/tfenv/2.2.2/version)`

If this is not yet implemented for newer versions could you please update the README file?
Or maybe point out if I'm doing something wrong.

**Comment by IsuruDilhan** [comment]
Facing the same issue here as well.
`$ docker run --rm -it -p 9000:9000 -v $(pwd):/src im2nguyen/rover
2021/09/24 11:09:13 Starting Rover...
2021/09/24 11:09:13 Initializing Terraform...
2021/09/24 11:09:16 Unable to parse Plan: terraform core version not supported by configuration`

**Comment by im2nguyen** [comment]
The [docker version of `rover`](https://github.com/im2nguyen/rover/blob/main/Dockerfile) uses the `hashicorp/terraform:light` docker image as a base, so it should be pulling in the latest version of Terraform.

I _think_ it's not working because your configuration explicitly uses `1.0.4` rather than `~> 1.0.4`, is this correct? 

The best way to resolve this is to download the `rover` binary and run it locally on your machine. This way, it uses the `terraform` binary on your local machine. I'm planning to release a homebrew formula soon so it's easy to install on locally for Macs to make this process easier.

**Comment by dmomcilo** [comment]
Yes, the local version works as expected, thanks, and no, since this is a test project I've been using newer versions of Terraform with `>= 1.0.4` condition. Also to mention I've tried with the `~> 1.0.4` condition and it does not work as well, so guess I'm goin "old school" with local binary :) .

**Comment by im2nguyen** [comment]
Oh that's strange. Will look into this more, thanks for reporting!
