### ISSUE TITLE
[Feature Request] Homebrew installation

### ISSUE THREAD

**Issue by im2nguyen** [im2nguyen/rover#31]

**Comment by SMillerDev** [comment]
I think I just did this for you: https://github.com/Homebrew/homebrew-core/pull/86711

**Comment by yu-iskw** [comment]
@SMillerDev Thank you for supporting it in Homebrew. I have an issue to install `terraform-rover` with brew, because I use `tfenv`, not `terraform` in Homebrew so that I have to switch terraform version based on the environment. Is there any workaround to avoid the error, even keeping to use `tfenv`?

```bash
Error: Cannot install terraform because conflicting formulae are installed.
  tfenv: because tfenv symlinks terraform binaries

Please `brew unlink tfenv` before continuing.
```
