### ISSUE TITLE
Proper versioning for Docker images

### ISSUE THREAD

**Issue by grafanalf** [im2nguyen/rover#43]
The only available tag for the Docker image is latest which makes difficult to layer on top of it.

**Comment by im2nguyen** [comment]
Hi @grafanalf,

Thanks for reporting. I just re-built and tagged the Docker images with the appropriate version. You can find a full list of supported versions [here](https://hub.docker.com/repository/docker/im2nguyen/rover/tags?page=1&ordering=last_updated). 

Future Docker images will be automatically built and tagged due to the [GH action](https://github.com/im2nguyen/rover/blob/main/.github/workflows/publishDockerImage.yml) @sujithq put together 😄 

Can you review and close the issue? Thanks!

**Comment by grafanalf** [comment]
Confirmed that tags work now. Thanks!
