### ISSUE TITLE
Support ARM (M1 mac)

### ISSUE THREAD

**Issue by murugaratham** [im2nguyen/rover#59]
Error response from daemon: image with reference im2nguyen/rover was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64

**Comment by im2nguyen** [comment]
Hrm, interesting. I built rover using go 1.17 which should have ARM (M1 mac) support. 

Based on the error message you provided, it seems like you installed the wrong binary version (`linux/ambd64`) instead of the actual one needed for your system (`linux/arm64`).

Here's the zip file for [rover v0.2.2 `linux/arm64`](https://github.com/im2nguyen/rover/releases/download/v0.2.2/rover_0.2.2_linux_arm64.zip)

**Comment by murugaratham** [comment]
I'm actually using docker, and it's most likely a problem with the docker images aren't built to be multi arch.

I have other applications written in .net that are built for arm64, but the base images themselves were built for amd64. Have yiu tried buildx?

**Comment by im2nguyen** [comment]
Oh! Then this is a dup of https://github.com/im2nguyen/rover/issues/50 😄 

I created a PR for it, but waiting for additional features I'm planning on adding this weekend so I can cut a release next week with more than one feature

**Comment by murugaratham** [comment]
I see, I'll close the issue and subscribe to  #50 then, thanks for linking them
